"""Report generator: render audit results as patient-friendly HTML or plain text."""

from __future__ import annotations

from datetime import date

from src.audit import AuditResult

_VERDICT_LABEL = {
    "supported": ("Supported by Evidence", "#2d6a2d"),
    "partially_supported": ("Partially Supported", "#7a5c00"),
    "unsupported": ("Not Clearly Supported", "#8b0000"),
    "insufficient_evidence": ("Insufficient Evidence", "#555"),
    "error": ("Review Required", "#555"),
}


def to_html(result: AuditResult, practice_name: str = "Your Dental Practice") -> str:
    """Render an AuditResult as a standalone HTML report."""
    today = date.today().isoformat()
    overall_label, overall_color = _VERDICT_LABEL.get(result.overall_assessment, ("Unknown", "#555"))

    procedures_html = ""
    for proc in result.procedures:
        label, color = _VERDICT_LABEL.get(proc.get("verdict", ""), ("Unknown", "#555"))
        flags_html = "".join(f"<li>{f}</li>" for f in proc.get("flags", []))
        citations_html = "".join(f"<li><em>{c}</em></li>" for c in proc.get("citations", []))
        procedures_html += f"""
        <div style="border:1px solid #ddd; border-radius:6px; padding:16px; margin-bottom:12px;">
          <h3 style="margin:0 0 4px">{proc.get('description', 'Procedure')}
            <span style="font-size:0.8em; color:{color}; margin-left:8px;">{label}</span>
          </h3>
          <code style="color:#777">{proc.get('cdt_code', '')}</code>
          <p style="margin:8px 0">{proc.get('rationale', '')}</p>
          {"<strong>Flags:</strong><ul>" + flags_html + "</ul>" if flags_html else ""}
          {"<strong>Evidence sources:</strong><ul>" + citations_html + "</ul>" if citations_html else ""}
        </div>"""

    missing_html = "".join(f"<li>{m}</li>" for m in result.missing_information)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ToothTrust Treatment Audit — {today}</title>
  <style>
    body {{ font-family: -apple-system, sans-serif; max-width: 720px; margin: 40px auto; padding: 0 20px; color: #222; }}
    h1 {{ color: #1a4e8a; }}
    .badge {{ display:inline-block; padding:4px 10px; border-radius:12px; font-size:0.85em; font-weight:600; color:{overall_color}; background:#f5f5f5; border:1px solid {overall_color}; }}
    footer {{ margin-top:40px; font-size:0.75em; color:#999; border-top:1px solid #eee; padding-top:12px; }}
  </style>
</head>
<body>
  <h1>Treatment Plan Audit</h1>
  <p><strong>Practice:</strong> {practice_name} &nbsp;|&nbsp; <strong>Date:</strong> {today}</p>
  <p><strong>Overall assessment:</strong> <span class="badge">{overall_label}</span>
     &nbsp; Confidence: {result.confidence}</p>

  <h2>Plain-Language Summary</h2>
  <p>{result.patient_summary}</p>

  <h2>Procedure-by-Procedure Review</h2>
  {procedures_html}

  {"<h2>What Would Help Us Be More Certain</h2><ul>" + missing_html + "</ul>" if missing_html else ""}

  <footer>
    This report is generated by ToothTrust and is informational only.
    It does not constitute a diagnosis or treatment recommendation.
    Always consult with your licensed dental provider.
    Evidence sourced from clinical guidelines and peer-reviewed literature.
  </footer>
</body>
</html>"""


def to_text(result: AuditResult) -> str:
    """Render an AuditResult as plain text (for voice read-back or logging)."""
    lines = [
        f"Treatment Plan Audit — {date.today().isoformat()}",
        f"Overall: {result.overall_assessment} (confidence: {result.confidence})",
        "",
        result.patient_summary,
        "",
    ]
    for proc in result.procedures:
        label = _VERDICT_LABEL.get(proc.get("verdict", ""), ("Unknown", ""))[0]
        lines.append(f"• {proc.get('description', 'Procedure')} [{proc.get('cdt_code', '')}]: {label}")
        if proc.get("flags"):
            for flag in proc["flags"]:
                lines.append(f"  Flag: {flag}")
    return "\n".join(lines)
